// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4UhUrcvSLjuXXW2qE2FW8f4sUkn4QT3c',
    appId: '1:334654773524:web:c62c666f74117cac9d8a01',
    messagingSenderId: '334654773524',
    projectId: 'nichibi01-20260610',
    authDomain: 'nichibi01-20260610.firebaseapp.com',
    storageBucket: 'nichibi01-20260610.firebasestorage.app',
    measurementId: 'G-7T2HD0HVYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDatAYEN9ALOgpMGkWzRtkmLjkd1W3tNVg',
    appId: '1:334654773524:android:079f95cefe29f0a39d8a01',
    messagingSenderId: '334654773524',
    projectId: 'nichibi01-20260610',
    storageBucket: 'nichibi01-20260610.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwVqRQXwmhE78mn9HYgHRd5DBRlf8TCOM',
    appId: '1:334654773524:ios:767ff13ed6e3ca909d8a01',
    messagingSenderId: '334654773524',
    projectId: 'nichibi01-20260610',
    storageBucket: 'nichibi01-20260610.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwVqRQXwmhE78mn9HYgHRd5DBRlf8TCOM',
    appId: '1:334654773524:ios:767ff13ed6e3ca909d8a01',
    messagingSenderId: '334654773524',
    projectId: 'nichibi01-20260610',
    storageBucket: 'nichibi01-20260610.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4UhUrcvSLjuXXW2qE2FW8f4sUkn4QT3c',
    appId: '1:334654773524:web:57cc7516e49183179d8a01',
    messagingSenderId: '334654773524',
    projectId: 'nichibi01-20260610',
    authDomain: 'nichibi01-20260610.firebaseapp.com',
    storageBucket: 'nichibi01-20260610.firebasestorage.app',
    measurementId: 'G-KP6CVLSZFM',
  );
}
